FROM bitwalker/alpine-erlang:latest

LABEL AUTHOR="Kailash K Yogeshwar <kailashyogeshwar85@gmail.com>"
LABEL TAG="latest"
LABEL REPO="lucifer8591/rabbit_erlangbase:latest"

RUN apk update && apk -U --no-cache add make gcc g++ curl net-tools wget tar libc6-compat bash xz xz-libs